version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "som@123"
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  api:
    image: som02511/fastapi
    container_name: api
    depends_on:
      - postgres
    ports:
      - "80:8000"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      SECRET_KEY: "${SECRET_KEY}"
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

volumes:
  postgres-db: