
services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "som@123"
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  api:
    build: .
    container_name: api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: "som@123"
      DATABASE_NAME: fastapi
      SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

volumes:
  postgres-db:
